import { getAirlines } from "@/lib/airlines";
import { guides } from "@/lib/guides";
import { getLinkStatus } from "@/lib/status";
import { getSiteUrl, repoUrl, siteName, siteLocales } from "@/lib/site";

export const dynamic = "force-static";

export function GET() {
  const airlines = getAirlines();
  const active = airlines.filter((airline) => getLinkStatus(airline.status) === "active").length;

  const lines = [
    `# ${siteName} — Full AI Access Guide`,
    "",
    `## About`,
    "",
    `${siteName} is a static-first, open-source directory of official airline-owned claim, compensation, refund, complaint, passenger-rights, and disruption-support links.`,
    "",
    "The project has no database, no authentication, no admin panel, no CMS, and no required environment variables. It is community-maintained through GitHub and deployed on Vercel.",
    "",
    "## Status Model",
    "",
    "Public link statuses:",
    "- `active`: available in the directory",
    "- `reported_broken`: community or checker flagged it as broken or outdated",
    "- `unknown`: unclear status or needs maintainer review",
    "",
    "## Dataset Summary",
    "",
    `- Total airlines: ${airlines.length}`,
    `- Active: ${active}`,
    `- Reported broken: ${airlines.filter((a) => getLinkStatus(a.status) === "reported_broken").length}`,
    `- Unknown: ${airlines.filter((a) => getLinkStatus(a.status) === "unknown").length}`,
    "",
    "## Complete Endpoint Reference",
    "",
    "### JSON APIs",
    `- **GET** ${getSiteUrl("/api/airlines")} — all airlines`,
    `- **GET** ${getSiteUrl("/api/airlines/{slug}")} — single airline`,
    `- **GET** ${getSiteUrl("/airlines.json")} — raw JSON file`,
    `- **GET** ${getSiteUrl("/api/meta")} — project metadata`,
    `- **GET** ${getSiteUrl("/openapi.json")} — OpenAPI 3.1 spec`,
    "",
    "### Markdown Endpoints",
    `- ${getSiteUrl("/airlines.md")} — full airline directory`,
    `- ${getSiteUrl("/airlines/{slug}.md")} — single airline Markdown`,
    `- ${getSiteUrl("/guides/index.md")} — all guides`,
    `- ${getSiteUrl("/contributing.md")} — contribution guide`,
    "",
    "### AI Discovery",
    `- ${getSiteUrl("/llms.txt")} — concise AI agent index`,
    `- ${getSiteUrl("/llms-full.txt")} — this file`,
    "",
    "### Available Locales",
    ...siteLocales.map((locale) => `- /${locale.code} (${locale.name}${locale.dir === "rtl" ? ", RTL" : ""})`),
    "",
    "### Guides",
    ...guides.map((guide) =>
      `- ${guide.title}: ${getSiteUrl(`/en/guides/${guide.slug}`)}`
    ),
    "",
    "### Tools",
    `- ${getSiteUrl("/en/tools/eligibility-helper")} — browser-only eligibility helper`,
    `- ${getSiteUrl("/en/tools/claim-template")} — browser-only claim template generator`,
    "",
    "## Airline Record Schema",
    "",
    "Each airline record includes:",
    "- `name` — airline name",
    "- `slug` — URL-safe identifier",
    "- `aliases` — alternative names and codes",
    "- `iata` (optional) — 2-char uppercase IATA code",
    "- `icao` (optional) — 3-char uppercase ICAO code",
    "- `country` (optional) — primary country",
    "- `region` (optional) — broad region",
    "- `claimUrl` — official airline claim/refund/complaint link",
    "- `officialSourceUrl` (optional) — proof source from airline website",
    "- `officialWebsiteUrl` (optional) — airline home page",
    "- `status` — internal status (`listed`, `verified`, `broken`, `unknown`)",
    "- `logoUrl`, `logoSourceUrl`, `logoStatus`, `logoNotes` (optional) — logo metadata",
    "- `listedAt` — ISO timestamp when added",
    "- `verifiedAt`, `verifiedBy` (optional) — verification metadata",
    "- `lastCheckedAt`, `lastCheckStatus` (optional) — last link check result",
    "- `notes` (optional) — maintainer notes",
    "",
    "## Contributing",
    "",
    `- [Add airline](${repoUrl}/issues/new?template=add-airline-link.yml)`,
    `- [Report broken](${repoUrl}/issues/new?template=report-broken-link.yml)`,
    `- [Suggest update](${repoUrl}/issues/new?template=update-airline-link.yml)`,
    `- [GitHub repo](${repoUrl})`,
    `- [Full contributing guide](${repoUrl}/blob/main/CONTRIBUTING.md)`,
    "",
    "Only official airline-owned links are accepted. No claims-management companies, affiliate links, middlemen, or link shorteners unless clearly airline-owned.",
    "",
    "## Licensing",
    "",
    "- Code: AGPL-3.0-or-later (see LICENSE-CODE.md)",
    "- Data: ODbL-1.0 (see LICENSE-DATA.md)",
    "- Brand: reserved (see TRADEMARKS.md)",
    "- Airline names/logos/trademarks belong to their respective owners.",
    "- See docs/licensing.md for a human-readable explanation.",
    "- See docs/attribution.md for data reuse attribution guidance.",
    "",
    "## Disclaimers",
    "",
    "- OpenFlightClaims is not legal advice.",
    "- External airline links can change at any time.",
    "- Verify links against official airline websites before use.",
    "- The project does not process claims and does not collect passenger personal data server-side.",
    "- Browser tools (eligibility helper, claim template) run locally and store nothing.",
    "",
    "---",
    `Generated at: ${new Date().toISOString()}`,
  ];

  return new Response(`${lines.join("\n")}\n`, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
